import './globals.css'
import Header from '../components/header'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { cookies as getCookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: '/images/react-firebase.svg',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await getData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers cookies={data.cookies}>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}

async function getData() {
  const cookies = String(getCookies())

  return {
    cookies,
  };
}
